import type { Metadata } from "next"

import "./globals.css"
import { cn } from "@/lib/utils"
import NavigationBar from "@/components/ui/navigationBar"
import MobileNavBar from "@/components/ui/mobileNavBar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
      
      )}
    >
      <body className="flex min-h-full flex-col gap-2">
        <header>
          <div className="hidden md:block">
            <NavigationBar />
          </div>
          <div className="md:hidden">
            <MobileNavBar />
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
